language: php

php:
  - 5.5

sudo: false

cache:
  directories:
    - ~/.composer/cache

install:
  - if [[ $TRAVIS_BRANCH = master ]]; then export COMPOSER_ROOT_VERSION=dev-master; else export COMPOSER_ROOT_VERSION=$TRAVIS_BRANCH.x-dev; fi;
  - composer install --prefer-dist --no-progress

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: 0ab85d09ea536dc6a7f03316b495cc078d8bee02c7c74974bbfd1fe280425a16

after_script:
  - ./bin/test-reporter
