language: php

php:
  - 5.4

sudo: false

before_install:
  - composer self-update
  - phpenv config-add .travis.php.ini


install:
  - composer install --prefer-dist --no-progress

script: ./bin/phpunit

after_script:
  - ./bin/ocular code-coverage:upload --access-token="0ab85d09ea536dc6a7f03316b495cc078d8bee02c7c74974bbfd1fe280425a16" --format=php-clover build/logs/clover.xml
