services:

    open_orchestra_theme.type.theme_choice:
        class: OpenOrchestra\ThemeBundle\Form\Type\ThemeChoiceType
        arguments:
            - %open_orchestra_theme.themes%
        tags:
            - { name: form.type, alias: orchestra_theme_choice }

    open_orchestra_theme.twig_extension.open_orchestra:
        class: OpenOrchestra\ThemeBundle\Twig\OpenOrchestraExtension
        arguments:
            - @templating.helper.assets
            - %open_orchestra_theme.themes%
        tags:
            - { name: twig.extension }

    open_orchestra_theme.subscriber.asset_package_injector:
        class: OpenOrchestra\ThemeBundle\EventSubscriber\AssetPackageInjectorSubscriber
        arguments:
            - @kernel
            - @assets.packages
            - @assets.empty_version_strategy
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: kernel.event_subscriber }
