services:

#--[FORM FIELDS]----------------#

    # Theme form field type
    open_orchestra_theme.type.theme_choice:
        class: OpenOrchestra\ThemeBundle\Form\Type\ThemeChoiceType
        arguments: ["%open_orchestra_theme.themes%"]
        tags: [{ name: form.type, alias: orchestra_theme_choice }]

#--[TWIG EXTENSIONS]-------------#

    open_orchestra_cms.twig.open_orchestra_extension:
        class: OpenOrchestra\ThemeBundle\Twig\OpenOrchestraExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    open_orchestra_cms.event.listener.assetpackage:
        class: OpenOrchestra\ThemeBundle\Event\Listener\HttpKernel\AssetPackageInjector
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
